### ISSUE TITLE
Template Tags and Filters don't work (i.e. join & last)

### ISSUE THREAD

**Issue by yankees9920** [alex/django-taggit#307]
Hello, it seems as though the built in template tags and filters, such as join, last, etc. do not work with the tags.

For example:

{{ tag.name|last }} displays the last letter of each tag, rather than the last tag
or 
{{ tag.name|join:", " }} displays each letter of the name seperated by a comma, rather than the each 

Thank you in advance.

**Comment by frewsxcv** [comment]
`tag.name` returns a `str`. Django filters works by altering the data on the left side of the `|`. In your examples above, since the left side of the `|` is a `str`, the template filters are going to do their calculations on the `str` instead of all `Tag`s. In your case, if you want the 'last tag', you should do that calculation in the view (or ideally a method on a `Manager`) and pass the result as a template variable. Let me know if you have any other questions
