### ISSUE TITLE
how to create tags programmatically?

### ISSUE THREAD

**Issue by evilplanet** [alex/django-taggit#527]
how to create tags programmatically? For example, in views.

```
tags_input = "hello, foo, bar, ok"
tagset = tag_parser(tags_input) # ['bar', 'foo', 'hello', 'ok']

obj = Post(title=title, tags=tagset)
obj.save()
```

The above snippet doesn't seem to work.

**Comment by edanvoye** [comment]
Have you tried calling set() ?

```
obj = Post(title=title)
obj.tags.set(*['bar', 'foo', 'hello', 'ok'])
obj.save()
```

**Comment by evilplanet** [comment]
I found `.add()` in the documentation:

```
apple = Food.objects.create(name="apple")
apple.tags.add("red", "green", "delicious")

```

I haven't tried `.set()`. What you described does seem better since I have to save the obj first before using `.add()`. What is that asterisk before the list?

**Comment by edanvoye** [comment]
The asterisk is simply to pass values from a list as separate parameters to a function.

```
def foo(a, b, c):
    print a+b+c
mylist = [1,2,3]
foo(*mylist)

```

**Comment by evilplanet** [comment]
I see. Thank you! So I don't have to save the object before calling `.set()`?

**Comment by edanvoye** [comment]
Oh, I see what you mean. Correcting my previous comment, I think you need to save before calling set(), because the ManyToMany relationship needs the id before it can be created. Is it possible that this would be the proper way, to create the least number of database access?

```
obj = Post(title=title)
obj.save()
obj.tags.set(*['bar', 'foo', 'hello', 'ok'])
```

save() needs to be called before creating a ManyToMany relationship, but it does not need to be called afterwards.

**Comment by evilplanet** [comment]
I see. Thank you!
